# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 04 Dec 2013 08:50:29 +0000
*               @ALL          1
*               @user         8
