<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: uahoo
 * Date: Tue, 15 Jul 2014 11:19:33 +0800
 */

$conf['title'] = 'Bash 脚本编程指南';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['plugin']['indexmenu']['show_sort'] = 1;

// end auto-generated content
