<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: uahoo
 * Date: Mon, 28 Apr 2014 17:39:23 +0800
 */

$conf['title'] = 'Shell Script 编程与应用';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['plugin']['indexmenu']['show_sort'] = 1;

// end auto-generated content
